export const proudOf = [
  "being a husband & father",
  "graduated with honors in computer engineering",
  "built vercel devrel during 1 → $200M ARR",
  "helped grow next.js community to 1.3+ million active devs",
  "seed investor in startups like fun, supabase, and linear",
  "can play guitar, piano, and drums (not at the same time)",
  "won a guitar hero lives the video game competition when I was 16",
  "won a state championship in track (high school glory days)",
  "currently have a 95 week inbox zero streak",
  "mentored dozens of developers who now work at top tech companies",
  "spoke at conferences across 15+ countries",
  "created open-source projects used by thousands of developers",
  "maintained a consistent writing habit for over 5 years",
  "built a personal brand that reaches millions of developers monthly"
]

export const believe = [
  "shipped fast beats the best strategy",
  "speed is a superpower",
  "create a bias toward shipping",
  "small teams ship faster",
  "ai-native teams will move 10x faster than those not willing to change",
  "landing > 3 launches (i.e. product adoption > shipping code)",
  "listen, build, ship, tell the customer, then repeat forever",
  "you have no career ceiling",
  "grit > talent",
  "there's no substitute for putting in the hours",
  "get 1% better every day",
  "be ruthlessly truth seeking",
  "the truth can be painful",
  "you can just change your mind if wrong",
  "have strong opinions, loosely held",
  "maximize your exposure hours",
  "'anarchist' > data",
  "consistency compounds over time",
  "focus on systems, not just goals",
  "embrace failure as a learning opportunity",
  "surround yourself with people smarter than you",
  "always be learning and adapting",
  "authenticity resonates more than perfection",
  "help others succeed and you'll succeed too",
  "document your journey for others to learn from"
]