export const proudOf = [
  "being a husband and father",
  "graduated with honors in software engineering",
  "building mantlz",
  "actually being a decent Fortnite player (haven't played in over 6 months)",
  "being pretty good at football (and any sport really)",
  "currently having a 95-week inbox zero streak",
  "continuing to do what I love",
  "creating open-source projects",
  "trying to be a better version of myself every day",
];

export const believe = [
  "shipping beats perfecting",
  "velocity is your competitive edge",
  "default to action over analysis",
  "AI-first companies will dominate the hesitant",
  "user adoption trumps feature count",
  "build, launch, learn, iterate endlessly",
  "your potential is limitless",
  "persistence outweighs natural ability",
  "hours invested compound into mastery",
  "improve incrementally every single day",
  "seek uncomfortable truths relentlessly",
  "reality stings but heals",
  "pivot when evidence demands it",
  "conviction with flexibility wins",
  "maximize time in the arena",
  "intuition beats spreadsheets",
  "daily habits create exponential results",
  "optimize processes, not just outcomes",
  "failures are expensive lessons",
  "hire people who intimidate you intellectually",
  "stay curious, stay relevant",
  "genuine beats polished every time",
  "lift others up to rise yourself",
  "share your struggles to inspire others",
];